server:
  port: 8088
spring:
  #静态资源处理
  resources:
    #启用默认静态资源处理，默认启用
    add-mappings: true
    cache:
      cachecontrol:
        #缓存响应时间，单位秒
        max-age: 3600
    chain:
      #资源链中启用缓存，默认启用
      cache: true
      #启用资源链，默认禁用
      enabled: true
      #启用压缩资源(gzip,brotli)解析,默认禁用
      compressed: true
      #启用H5应用缓存，默认禁用
      html-application-cache: true
      #静态资源位置
    static-locations: classpath:/static/
#  关闭thymeleaf缓存
  thymeleaf:
    cache: false
#    数据库配置
  dataSource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      #      连接池
      pool-name: DateHikariCP
#      最小连接数
      minimum-idle: 5
#      空闲连接最大时间 默认600000（10分钟）
      idle-timeout: 180000
#      最大连接数，默认10
      maximum-pool-size: 10
#      从连接池返回的链接自动提交
      auto-commit: true
#      连接最大存活时间，0表示永久存活默认1800000（半小时）
      max-lifetime: 1800000
#      链接超时时间默认30000（30s）
      connection-timeout: 30000
#      心跳机制 测试是否可用的查询语句
      connection-test-query: SELECT 1
#      redis配置
  redis:
#    服务器地址
    host: 127.0.0.1
#    端口
    port: 6379
#    数据库
    database: 0
#    超时时间
    timeout: 10000
    lettuce:
      pool:
#        最大连接数
        max-active: 8
#        最大等待时间默认-1不等待
        max-wait: 1000ms
#        最大空闲链接默认8
        max-idle: 200
#        最小空闲连接默认8
        min-idle: 5
#  Rabbitmq
  rabbitmq:
#    服务器
    host: localhost
#    用户名
    username: guest
#    密码
    password: guest
#    虚拟主机
    virtual-host: /
#    端口
    port: 5672
    listener:
      simple:
#消费者最小数量
        concurrency: 10
#        消费者最大数量
        max-concurrency: 10
#        限制消费者每次只处理一条消息，处理完毕继续吓一跳消息
        prefetch: 1
#        启动时默认启动容器 默认true
        auto-startup: true
#        被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
#        发布重试 默认false
        enabled: true
#        重试时间默认1000ms
        inital-interval: 1000ms
#        重试最大次数 默认3
        max-attempts: 3
#        重试最大时间
        max-interval: 10000ms
#        重试的间隔乘数 2.0  1 10s 2 20s 3 40s
        multiplier: 1

# Mybatis-plus配置
mybatis-plus:
#  配置mapper.xml映射文件
  mapper-location: classpath*:/mapper/*Mapper.xml
#  配置mybatis数据返回类型别名（默认是类名）
  type-aliases-package: com.study.seckill.pojo
#Mybatis Sql 打印（方法接口所在的包，不是mapper.xml的包）
logging:
  level:
    com.study.seckill.mapper: debug

cors:
  allowedOrigins: http://127.0.0.1:5500